### ISSUE TITLE
cannot read property 'download' of undefined 

### ISSUE THREAD

**Issue by harshsrivastavaglobussoft** [plrthink/react-native-file-download#11]
var RNFileDownload = NativeModules.RNFileDownload;
var promisify = require("es6-promisify")

let progressEventName = 'RNFileDownloadProgress'
let progressEventTable = {}
var _download = promisify(RNFileDownload.download)

var _error = (err) => {
  throw err
}
in index.ios.js file of package line number 12 

I am using 
"react": "16.0.0-alpha.12",
"react-native": "0.47.2",
xcode-8.3.2

**Comment by plrthink** [comment]
I think it's because this package doesn't work with rn>0.39 on iOS. But also note that this library is marked as DEPRECATED. So I'm not going to fix this and please use other libraries for your use case, like [react-native-fs](https://github.com/itinance/react-native-fs#downloadfileoptions-downloadfileoptions--jobid-number-promise-promisedownloadresult-)
